[default]
DEBUG = true
TITLE = "SYS SALES PYTHON"

SQLALCHEMY_DATABASE_URI = 'sqlite:///data/database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false

EXTENSIONS = [
    "app.extensions.flask_sqlalchemy",
    "app.extensions.flask_marshmallow",
    
    "app.blueprints.api",
]